# Generated by Django 5.0.7 on 2024-07-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="movies_series_name",
            field=models.CharField(default="The Boys", max_length=50),
        ),
    ]
