# Generated by Django 5.0.7 on 2024-07-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_review_movies_series_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="movies_series_name",
            field=models.CharField(default="Matrix", max_length=50),
        ),
    ]
