# Generated by Django 5.0.7 on 2024-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0005_rename_text_review_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="description",
            new_name="text",
        ),
        migrations.AlterField(
            model_name="review",
            name="movies_series_name",
            field=models.CharField(default="Movie or Series Name", max_length=50),
        ),
    ]
