# Generated by Django 5.0.7 on 2024-07-25 14:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0006_rename_description_review_text_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="review",
            new_name="EReview",
        ),
    ]
