# Generated by Django 5.0.7 on 2024-07-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0007_rename_review_ereview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ereview",
            name="movies_series_name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
